### ISSUE TITLE
joy of painting

### ISSUE THREAD

**Issue by Birbs-world** [Birbs-world/RVT-Gaming-3#22]

**Comment by Birbs-world** [comment]
not going to be added as it is a fabric mod and i don't want to have to add/maintain the fabric -> neoforge compatibility layer for one mod to work

**Comment by PastellePixie** [comment]
There's a Forge version, just no Neo-Forge, at least not yet. Also Xerca is a very nice dev, he might just port it to what you need.

**Comment by Birbs-world** [comment]
> There's a Forge version, just no Neo-Forge
the RVT Gaming Pack is for 1.21.1 (neoforge) the forge version ended support in 1.20.1, and on neoforge it does work with the compatibility layer
additionally this was a mod suggestion buy one of the members in the discord lol
